
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import ObserverProvider from "./context/ObserverProvider";
import ThemeProvider from "./context/ThemeProvider";
import SidebarProvider from "./context/SidebarProvider";
// import ObserverProvider from "./providers/observer/ObserverProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
   subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)


{
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased transition-colors duration-1500 text-neutral-900 dark:bg-neutral-900 dark:text-neutral-100`}
      >
         <ThemeProvider 
            attribute='class' 
            enableSystem 
            defaultTheme="system"
            disableTransitionOnChange
            enableColorScheme = {false}
         >
            <ObserverProvider>
               <SidebarProvider>
                  {children}
               </SidebarProvider>
            </ObserverProvider>
         </ThemeProvider>
      </body>
    </html>
  );
}
